server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncode=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis:
  configuration:
    database-id: mysql
logging:
  level:
    com.zhuyj.mall: debug
